import type { Options, Pattern } from "../../../core/types";
import { generate as generateBase } from "./generate";
import { generate as generatePreview } from "./generate.preview";

// Generate entrypoint for the pattern. This function is roughly the same for all patterns.
export async function generate(options: Options) {
  // Base generation logic, this is the same for both runtime and preview. As much as possible should be done here.
  const baseRes = await generateBase(options);

  if (options.env === "preview") {
    // Add any necessary preview generation, these would be mock files to replace what's generated by the filesystem generation.
    const previewRes = await generatePreview(options);
    return {
      ...baseRes,
      ...previewRes,
    };
  }

  // Write the create files to the filesystem
  // Install packages
  // Install shadcn-svelte components (replace components array with the returned array containing only the new components)

  // Runtime generation. Any database or file modifications should be done here.
  const { generate: generateRuntime } = await import("./generate.runtime");
  const runtimeRes = await generateRuntime(options);
  return {
    ...baseRes,
    ...runtimeRes,
  };
}

export default {
  slug: "generate-form",
  title: "Generate a form",
  summary: "Generates a form.",
  categories: ["forms"],
  tags: ["sveltekit", "superforms", "validation", "zod"],

  command: {
    raw: "vela generate form contact name:text email:email message:textarea",
    argv: [
      "generate",
      "form",
      "contact",
      "name:text",
      "email:email",
      "message:textarea",
    ],
  },

  baseline: "velastack",

  generate: generate,
} satisfies Pattern;
