import { existsSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { REPO_ROOT, velaBin } from "./baseline";
import { npmBin, npxBin } from "./exec";
import { detectFeatures } from "./features";
import type { ErrorRecord } from "./apply";
import type { Project } from "./project";

export interface Diagnostic {
  type: "ERROR" | "WARNING";
  file: string;
  /** 1-based. */
  line: number;
  /** 1-based. */
  col: number;
  code: string | number;
  message: string;
  source: string;
}

export interface ParsedCheck {
  diagnostics: Diagnostic[];
  completed: boolean;
  failure?: string;
}

export interface CheckReport {
  errors: ErrorRecord[];
  /** Every error-level diagnostic svelte-check produced, before filtering. */
  diagnostics: Diagnostic[];
}

export interface CheckOptions {
  /** Diagnostic keys already present before the case started; not the pattern's fault. */
  baselineDiagnostics?: Set<string>;
  /** Also run `vela test:server` (slow; opt-in). */
  serverTests?: boolean;
}

export const CHECK_TSCONFIG = "tsconfig.check.json";

/**
 * TypeScript codes for "declared but never used". With `noUnusedLocals` these
 * come back as errors; they are the unused-variable signal the harness wants.
 */
export const UNUSED_CODES = new Set([6133, 6192, 6196, 6198, 6205]);

export function diagnosticKey(d: Diagnostic): string {
  return `${d.file}|${d.code}|${d.line}|${d.message}`;
}

export function formatDiagnostic(d: Diagnostic): string {
  return `${d.file}:${d.line}:${d.col} ${d.source}(${d.code}) ${d.message}`;
}

/**
 * The project's own tsconfig plus the unused-locals rule. `exclude` is left
 * alone: overriding it would drop the SvelteKit-generated list, and
 * svelte-check's `--ignore` only works without a tsconfig, so exclusions are
 * applied to the parsed diagnostics instead (`isIgnorable`).
 */
export function writeCheckTsconfig(root: string): void {
  writeFileSync(
    path.join(root, CHECK_TSCONFIG),
    JSON.stringify(
      {
        extends: "./tsconfig.json",
        compilerOptions: { noUnusedLocals: true },
      },
      null,
      2,
    ) + "\n",
  );
}

/** Parses `svelte-check --output machine-verbose` (one `<ms> <row>` per line). */
export function parseMachineVerbose(stdout: string): ParsedCheck {
  const diagnostics: Diagnostic[] = [];
  let completed = false;
  let failure: string | undefined;

  for (const rawLine of stdout.split(/\r?\n/)) {
    const match = /^\d+\s+(.*)$/.exec(rawLine.trim());
    if (!match) continue;
    const row = match[1];
    if (row.startsWith("START")) continue;
    if (row.startsWith("COMPLETED")) {
      completed = true;
      continue;
    }
    if (row.startsWith("FAILURE")) {
      failure = row.slice("FAILURE".length).trim();
      continue;
    }
    if (!row.startsWith("{")) continue;

    let parsed: {
      type: string;
      filename?: string;
      fn?: string;
      start?: { line: number; character: number };
      message: string;
      code: string | number;
      source?: string;
    };
    try {
      parsed = JSON.parse(row);
    } catch {
      continue;
    }
    if (parsed.type !== "ERROR" && parsed.type !== "WARNING") continue;
    diagnostics.push({
      type: parsed.type,
      file: (parsed.filename ?? parsed.fn ?? "").replace(/\\/g, "/"),
      line: (parsed.start?.line ?? 0) + 1,
      col: (parsed.start?.character ?? 0) + 1,
      code: parsed.code,
      message: parsed.message,
      source: parsed.source ?? "",
    });
  }

  return { diagnostics, completed, failure };
}

let customComponentsCache: Set<string> | undefined;

/** Component directories this repo ships under `src/ui/components`; everything else in `src/lib/components/ui` is a public shadcn-svelte component. */
export function customComponents(): Set<string> {
  customComponentsCache ??= new Set(
    readdirSync(path.join(REPO_ROOT, "src", "ui", "components"), {
      withFileTypes: true,
    })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name),
  );
  return customComponentsCache;
}

/**
 * Diagnostics that are not a pattern's responsibility:
 * - anything under `src/locales/` (generated by wuchale);
 * - unused-variable diagnostics inside public shadcn-svelte components (we
 *   install them verbatim; genuine type errors there still count).
 */
export function isIgnorable(
  d: Diagnostic,
  custom: Set<string> = customComponents(),
): boolean {
  if (d.file.startsWith("src/locales/")) return true;
  const ui = /^src\/lib\/components\/ui\/([^/]+)\//.exec(d.file);
  if (ui && !custom.has(ui[1]) && UNUSED_CODES.has(Number(d.code))) {
    return true;
  }
  return false;
}

/**
 * The per-step gate: sync, type-check with unused-locals, format-check the
 * files the pattern wrote, and optionally run the generated server tests.
 * Returns error records rather than throwing so a case can report everything
 * at once.
 */
export function runChecks(
  project: Project,
  label: string,
  changedFiles: string[],
  opts: CheckOptions = {},
): CheckReport {
  const root = project.root;
  const errors: ErrorRecord[] = [];
  const tag = label.replace(/[^a-zA-Z0-9._-]+/g, "-");

  project.run(npxBin(), ["svelte-kit", "sync"]);
  if (detectFeatures(root).backend) {
    project.run(velaBin(), ["sync"]);
  }

  writeCheckTsconfig(root);
  const check = project.run(
    npxBin(),
    [
      "svelte-check",
      "--tsconfig",
      `./${CHECK_TSCONFIG}`,
      "--output",
      "machine-verbose",
      "--threshold",
      "error",
    ],
    { allowFailure: true },
  );
  writeFileSync(
    path.join(project.logDir, `${tag}.svelte-check.jsonl`),
    check.stdout + (check.stderr ? `\n--- stderr\n${check.stderr}` : ""),
  );

  const parsed = parseMachineVerbose(check.stdout);
  if (parsed.failure) {
    errors.push({
      kind: "check",
      message: `svelte-check failed: ${parsed.failure}`,
    });
  } else if (!parsed.completed) {
    errors.push({
      kind: "check",
      message: `svelte-check did not complete (exit ${check.status}):\n${(check.stderr || check.stdout).trim().slice(-4000)}`,
    });
  }

  const diagnostics = parsed.diagnostics.filter((d) => d.type === "ERROR");
  const baseline = opts.baselineDiagnostics ?? new Set<string>();
  for (const d of diagnostics) {
    if (isIgnorable(d) || baseline.has(diagnosticKey(d))) continue;
    errors.push({ kind: "check", message: formatDiagnostic(d) });
  }

  const existingChanged = [...new Set(changedFiles)].filter((file) =>
    existsSync(path.join(root, file)),
  );
  if (existingChanged.length > 0) {
    const prettier = project.run(
      npxBin(),
      ["prettier", "--check", "--ignore-unknown", ...existingChanged],
      { allowFailure: true },
    );
    if (prettier.status !== 0) {
      const unformatted = prettier.stderr
        .split(/\r?\n/)
        .map((line) => line.replace(/^\[warn\]\s*/, "").trim())
        .filter((line) => existingChanged.includes(line));
      errors.push({
        kind: "prettier",
        message:
          unformatted.length > 0
            ? `not formatted: ${unformatted.join(", ")}`
            : `prettier --check failed:\n${(prettier.stderr || prettier.stdout).trim().slice(-2000)}`,
      });
    }
  }

  if (opts.serverTests ?? process.env.INTEGRATION_SERVER_TESTS === "1") {
    const tests = project.run(npmBin(), ["run", "test:server"], {
      allowFailure: true,
    });
    // `vela test:server` exits with vitest's own code, so the status is the verdict.
    if (tests.status !== 0) {
      const output = `${tests.stdout}\n${tests.stderr}`;
      errors.push({
        kind: "server-tests",
        message: `exit ${tests.status}:\n${output.trim().slice(-4000)}`,
      });
    }
  }

  if (errors.length === 0) {
    rmSync(path.join(root, CHECK_TSCONFIG), { force: true });
  }

  return { errors, diagnostics };
}
